#!/usr/bin/env bash
#TCP and UDP ports
# Get a list of all listening sockets
listening_sockets=$(ss -lntu | awk 'NR>1 {print $NF}')
for socket in $listening_sockets; do
  pid=$(lsof -i $socket | awk 'NR>1 {print $2}')
  process=$(ps -p $pid -o comm=)
done